backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
#  name: github
#  repo: TheFullResolution/graweria

media_folder: 'static/images/uploads'
public_folder: '/uploads'

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Meta Data'
        name: 'metaData'
        file: cms/content/metaData.json
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - {
              label: Description,
              name: description,
              widget: string,
              required: true,
            }
          - label: 'Links'
            name: 'links'
            widget: 'object'
            collapsed: true
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - { label: Home, name: home, widget: string, required: true }
              - {
                  label: Contact,
                  name: contact,
                  widget: string,
                  required: true,
                }
              - {
                  label: Products,
                  name: products,
                  widget: string,
                  required: true,
                }
              - { label: About, name: about, widget: string, required: true }
          - label: 'Address'
            name: 'address'
            widget: 'object'
            collapsed: true
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - { label: Street, name: street, widget: string, required: true }
              - { label: City, name: city, widget: string, required: true }
              - {
                  label: Postcode,
                  name: postcode,
                  widget: string,
                  required: true,
                }
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            collapsed: true
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - { label: Phone, name: phone, widget: string, required: true }
              - { label: Email, name: email, widget: string, required: true }
          - label: 'Opening Hours'
            name: 'openingHours'
            widget: 'object'
            collapsed: true
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - label: 'Hours'
                name: 'list'
                widget: 'list'
                summary: '{{fields.days}} - {{fields.hours}}'
                fields:
                  - { label: Days, name: days, widget: string, required: true }
                  - {
                      label: Hours,
                      name: hours,
                      widget: string,
                      required: true,
                    }
          - label: 'Banner'
            name: 'banner'
            widget: 'image'
      - label: 'Home'
        name: 'home'
        file: cms/content/home.json
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: SubTitle, name: subtitle, widget: string, required: true }
          - { label: Description, name: description, widget: markdown }
          - label: 'Side Picture'
            name: 'sidePicture'
            widget: 'image'
          - { label: Read More, name: readmore, widget: string, required: true }
      - label: 'Blog'
        name: 'blog'
        file: cms/content/blog.json
        fields:
          - { label: Return Label, name: return, widget: string, required: true }
          - label: 'Default Picture'
            name: 'default_pic'
            widget: 'image'
            required: true
      - label: 'About'
        name: 'about'
        file: cms/content/about.json
        fields:
         - { label: Title, name: title, widget: string, required: true }
         - { label: Description, name: description, widget: markdown }
         - { label: Video Title, name: videoTitle, widget: string }
         - { label: Video Url, name: videoSrcURL, widget: string }
         - label: 'Pictures'
           name: 'gallery'
           widget: 'list'
           fields:
             - { label: Label, name: label, widget: string }
             - label: 'Image'
               name: 'image'
               widget: 'image'
               required: true
      - label: 'Not Found'
        name: 'notfound'
        file: cms/content/notfound.json
        fields:
          - { label: Go Home Label, name: go_home_label, widget: string, required: true }
          - { label: Text, name: text, widget: string, required: true }
          - label: 'Picture'
            name: 'picture'
            widget: 'image'
            required: true
  - name: 'blog'
    label: 'Blog'
    folder: 'cms/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Content Key',
          name: 'contentKey',
          widget: 'hidden',
          default: 'blog',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'startDate',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Expire Date',
          name: 'endDate',
          widget: 'datetime',
          required: true,
        }
      - label: 'Banner'
        name: 'banner'
        widget: 'image'
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          buttons:
            [
              bold,
              italic,
              link,
              heading-one,
              heading-two,
              heading-three,
              quote,
              bulleted-list,
              numbered-list,
            ],
          editor_components: ['image'],
          required: true,
        }
