backend:
  name: github
  repo: TheFullResolution/graweria

media_folder: 'static/images/uploads'
public_folder: '/uploads'

collections:
  - label: 'Pages PL'
    name: 'pl-pages'
    files:
      - label: 'Meta Data'
        name: 'metaData'
        file: cms/content/metaData.json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: 'Links'
            name: 'links'
            widget: 'object'
            collapsed: true
            fields:
              - { label: Home, name: home, widget: string }
              - { label: Contact, name: contact, widget: string }
              - { label: Products, name: products, widget: string }
          - label: 'Banner'
            name: 'banner'
            widget: 'image'
            media_library:
              config:
                multiple: false
      - label: 'Home'
        name: 'home'
        file: cms/content/home.json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
  - name: 'blog'
    label: 'Blog'
    folder: 'cms/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Content Key',
          name: 'contentKey',
          widget: 'hidden',
          default: 'blog',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'start-date', widget: 'datetime' }
      - { label: 'Expire Date', name: 'end-date', widget: 'datetime' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          buttons:
            [
              bold,
              italic,
              link,
              heading-one,
              heading-two,
              heading-three,
              quote,
              bulleted-list,
              numbered-list,
            ],
          editor_components: ['image'],
        }
